=== yamagenii/test-portlet/jetspeed/src/main/resources/org/apache/jetspeed/services/db/repository.dtd
<!--
	ObJectRelationalBridge - Bridging Java objects and relational dabatases

	This DTD describes the grammar of the Descriptor repository

	Author: Thomas Mahler, (c) 2000, 2001, 2002

-->
<!ELEMENT MappingRepository (JdbcConnectionDescriptor, ClassDescriptor+)>
<!ELEMENT JdbcConnectionDescriptor (dbms.name, jdbc.level?, ((driver.name, url.protocol, url.subprotocol, url.dbalias) | datasource.name), user.name?, user.passwd?)>
<!ELEMENT ClassDescriptor (ExtentDescriptor|(JdbcConnectionDescriptor?,  class.name, class.proxy?, class.extent*, schema.name?, table.name, orderby?, conversionStrategy?, rowReader?, FieldDescriptor+, ReferenceDescriptor*, CollectionDescriptor*))>
<!ELEMENT FieldDescriptor (field.name, column.name, jdbc_type, PrimaryKey?, autoincrement?, locking?)>
<!ELEMENT ReferenceDescriptor (rdfield.name, referenced.class, fk_descriptor_ids, auto.retrieve?, auto.update?, auto.delete?, refreshReference? )>
<!ELEMENT CollectionDescriptor (cdfield.name, items.class, inverse_fk_descriptor_ids, collection.class?, proxy?, auto.retrieve?, auto.update?, auto.delete?, indirection_table?, fks_pointing_to_this_class?, fks_pointing_to_items_class?, orderby?, refreshCollection?)>
<!ELEMENT ExtentDescriptor (class.name, class.extent+)>
<!ELEMENT dbms.name (#PCDATA)>
<!ELEMENT jdbc.level (#PCDATA)>
<!ELEMENT driver.name (#PCDATA)>
<!ELEMENT url.protocol (#PCDATA)>
<!ELEMENT url.subprotocol (#PCDATA)>
<!ELEMENT url.dbalias (#PCDATA)>
<!ELEMENT datasource.name (#PCDATA)>
<!ELEMENT schema.name (#PCDATA)>
<!ELEMENT user.name (#PCDATA)>
<!ELEMENT user.passwd (#PCDATA)>
<!ELEMENT class.name (#PCDATA)>
<!ELEMENT class.proxy (#PCDATA)>
<!ELEMENT table.name (#PCDATA)>
<!ELEMENT field.name (#PCDATA)>
<!ELEMENT column.name (#PCDATA)>
<!ELEMENT jdbc_type (#PCDATA)>
<!ELEMENT PrimaryKey (#PCDATA)>
<!ELEMENT autoincrement (#PCDATA)>
<!ELEMENT locking (#PCDATA)>
<!ELEMENT rdfield.name (#PCDATA)>
<!ELEMENT referenced.class (#PCDATA)>
<!ELEMENT fk_descriptor_ids (#PCDATA)>
<!ELEMENT inverse_fk_descriptor_ids (#PCDATA)>
<!ELEMENT proxy (#PCDATA)>
<!ELEMENT auto.retrieve (#PCDATA)>
<!ELEMENT auto.update (#PCDATA)>
<!ELEMENT auto.delete (#PCDATA)>
<!ELEMENT cdfield.name (#PCDATA)>
<!ELEMENT items.class (#PCDATA)>
<!ELEMENT collection.class (#PCDATA)>
<!ELEMENT indirection_table (#PCDATA)>
<!ELEMENT fks_pointing_to_this_class (#PCDATA)>
<!ELEMENT fks_pointing_to_items_class (#PCDATA)>
<!ELEMENT class.extent (#PCDATA)>
<!ELEMENT orderby (#PCDATA)>
<!ELEMENT conversionStrategy (#PCDATA)>
<!ELEMENT rowReader (#PCDATA)>
<!ELEMENT refreshCollection (#PCDATA)>
<!ELEMENT refreshReference (#PCDATA)>

<!ATTLIST JdbcConnectionDescriptor id CDATA #IMPLIED>
<!ATTLIST ClassDescriptor
	id CDATA #IMPLIED
	isolation CDATA #IMPLIED
>
<!ATTLIST FieldDescriptor id CDATA #IMPLIED>
<!ATTLIST ReferenceDescriptor id CDATA #IMPLIED>
<!ATTLIST CollectionDescriptor id CDATA #IMPLIED>

<!ATTLIST orderby sort CDATA #IMPLIED>

=== yamagenii/test-portlet/jetspeed/src/main/resources/org/apache/jetspeed/services/db/repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MappingRepository SYSTEM "repository.dtd">

<MappingRepository>
<!-- The Default JDBC Connection. If a Class does not specify its own JDBC Connection,
     the Connection specified here will be used. -->

   <JdbcConnectionDescriptor id="default">
      <dbms.name>Oracle8i</dbms.name>
      <driver.name>oracle.jdbc.driver.OracleDriver</driver.name>
      <url.protocol>jdbc</url.protocol>
      <url.subprotocol>oracle:thin</url.subprotocol>
      <url.dbalias>jdbc:oracle:thin:@nirvana:1521:bluesun3</url.dbalias>
      <user.name>jetspeed</user.name>
      <user.passwd>jetspeed</user.passwd>
   </JdbcConnectionDescriptor>
   
   <!--JdbcConnectionDescriptor id="default">
      <dbms.name>JNDI Sample Entry</dbms.name>
      <datasource.name>jndi_lookup_name</datasource.name>
      <user.name>sa</user.name>
      <user.passwd></user.passwd>
   </JdbcConnectionDescriptor-->

   <!--JdbcConnectionDescriptor id="default">
      <dbms.name>InstantDB</dbms.name>
      <driver.name>com.lutris.instantdb.jdbc.idbDriver</driver.name>
      <url.protocol>jdbc</url.protocol>
      <url.subprotocol>idb</url.subprotocol>
      <url.dbalias>..\\setup\\demo.prp</url.dbalias>
   </JdbcConnectionDescriptor-->

   <!--JdbcConnectionDescriptor id="default">
      <dbms.name>Db2</dbms.name>
      <driver.name>COM.ibm.db2.jdbc.app.DB2Driver</driver.name>
      <url.protocol>jdbc</url.protocol>
      <url.subprotocol>db2</url.subprotocol>
      <url.dbalias>dbwte001</url.dbalias>
      <user.name>db2admin</user.name>
      <user.passwd>db2</user.passwd>
   </JdbcConnectionDescriptor-->

   <!--JdbcConnectionDescriptor id="default">
      <dbms.name>Oracle</dbms.name>
      <driver.name>oracle.jdbc.driver.OracleDriver</driver.name>
      <url.protocol>jdbc</url.protocol>
      <url.subprotocol>oracle:oci8</url.subprotocol>
      <url.dbalias>@(description=(address=(host=127.0.0.1)(protocol=tcp)(port=1521))(connect_data=(sid=orcl)))</url.dbalias>
      <user.name>scott</user.name>
      <user.passwd>tiger</user.passwd>
   </JdbcConnectionDescriptor-->

   <!--JdbcConnectionDescriptor id="default">
       <dbms.name>PostgreSQL</dbms.name>
       <driver.name>org.postgresql.Driver</driver.name>
       <url.protocol>jdbc</url.protocol>
       <url.subprotocol>postgresql</url.subprotocol>
       <url.dbalias>ojbdemodb</url.dbalias>
       <user.name>username</user.name>
       <user.passwd>passwd</user.passwd>
    </JdbcConnectionDescriptor-->


    <!--JdbcConnectionDescriptor id="default">
        <dbms.name>MySQL</dbms.name>
        <driver.name>org.gjt.mm.mysql.Driver</driver.name>
        <url.protocol>jdbc</url.protocol>
        <url.subprotocol>mysql</url.subprotocol>
        <url.dbalias>//localhost:3306/test</url.dbalias>
        <user.name>foo</user.name>
        <user.passwd>bar</user.passwd>
    </JdbcConnectionDescriptor-->

    <!--JdbcConnectionDescriptor id="default">
        <dbms.name>MsAccess</dbms.name>
        <jdbc.level>1.0</jdbc.level>
        <driver.name>sun.jdbc.odbc.JdbcOdbcDriver</driver.name>
        <url.protocol>jdbc</url.protocol>
        <url.subprotocol>odbc</url.subprotocol>
        <url.dbalias>OJB</url.dbalias>
    </JdbcConnectionDescriptor-->

    <!--JdbcConnectionDescriptor id="default">
        <dbms.name>Informix</dbms.name>
        <jdbc.level>1.0</jdbc.level>
        <driver.name>com.informix.XXX</driver.name>
        <url.protocol>jdbc</url.protocol>
        <url.subprotocol>XXX</url.subprotocol>
        <url.dbalias>XXX</url.dbalias>
    </JdbcConnectionDescriptor-->

<!-- Definitions for org.apache.jetspeed.services.registry.base.BaseMediaTypeEntry -->
   <ClassDescriptor id="1">
      <class.name>org.apache.jetspeed.om.registry.base.BaseMediaTypeEntry</class.name>
      <table.name>MEDIATYPE</table.name>
      <FieldDescriptor id="1">
         <field.name>id</field.name>
         <column.name>id</column.name>
         <jdbc_type>BIGINT</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
         <autoincrement>true</autoincrement>
      </FieldDescriptor>
      <FieldDescriptor id="2">
         <field.name>name</field.name>
         <column.name>name</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="3">
         <field.name>_hidden</field.name>
         <column.name>hidden</column.name>
         <jdbc_type>INTEGER</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="4">
         <field.name>mimeType</field.name>
         <column.name>mimetype</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="5">
         <field.name>title</field.name>
         <column.name>title</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="6">
         <field.name>description</field.name>
         <column.name>description</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="7">
         <field.name>image</field.name>
         <column.name>image</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="8">
         <field.name>role</field.name>
         <column.name>role</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
   </ClassDescriptor>

<!-- Definitions for org.apache.jetspeed.services.registry.base.BaseSkinEntry -->
   <ClassDescriptor id="2">
      <class.name>org.apache.jetspeed.om.registry.base.BaseSkinEntry</class.name>
      <table.name>SKIN</table.name>
      <FieldDescriptor id="1">
         <field.name>id</field.name>
         <column.name>id</column.name>
         <jdbc_type>BIGINT</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
         <autoincrement>true</autoincrement>
      </FieldDescriptor>
      <FieldDescriptor id="2">
         <field.name>name</field.name>
         <column.name>name</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="3">
         <field.name>_hidden</field.name>
         <column.name>hidden</column.name>
         <jdbc_type>INTEGER</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="4">
         <field.name>title</field.name>
         <column.name>title</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="5">
         <field.name>description</field.name>
         <column.name>description</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="6">
         <field.name>image</field.name>
         <column.name>image</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="7">
         <field.name>role</field.name>
         <column.name>role</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
      </FieldDescriptor>
   </ClassDescriptor>


<!-- OJB INTERNAL MAPPINGS START HERE, DO NOT EDIT -->

<!-- The OJB SequenceManagerTable -->
   <ClassDescriptor id="1027">
      <class.name>ojb.broker.util.SequenceEntry</class.name>
      <table.name>OJB_SEQ</table.name>
      <FieldDescriptor id="1">
         <field.name>classname</field.name>
         <column.name>CLASSNAME</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="2">
         <field.name>fieldname</field.name>
         <column.name>FIELDNAME</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="3">
         <field.name>current</field.name>
         <column.name>LAST_NUM</column.name>
         <jdbc_type>INTEGER</jdbc_type>
      </FieldDescriptor>
   </ClassDescriptor>

<!-- The OJB HIGH/LOW SequenceManagerTable -->
   <ClassDescriptor id="1099">
      <class.name>ojb.broker.util.HighLowSequence</class.name>
      <table.name>OJB_HL_SEQ</table.name>
      <FieldDescriptor id="1">
         <field.name>className</field.name>
         <column.name>CLASSNAME</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="2">
         <field.name>fieldName</field.name>
         <column.name>FIELDNAME</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="3">
         <field.name>maxKey</field.name>
         <column.name>MAX_KEY</column.name>
         <jdbc_type>INTEGER</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="4">
         <field.name>grabSize</field.name>
         <column.name>GRAB_SIZE</column.name>
         <jdbc_type>INTEGER</jdbc_type>
      </FieldDescriptor>
   </ClassDescriptor>



<!-- The OJB Lock Table -->
   <ClassDescriptor id="1100">
      <class.name>ojb.odmg.locking.LockEntry</class.name>
      <table.name>OJB_LOCKENTRY</table.name>
      <FieldDescriptor id="1">
         <field.name>oidString</field.name>
         <column.name>OID_</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="2">
         <field.name>transactionId</field.name>
         <column.name>TX_ID</column.name>
         <jdbc_type>VARCHAR</jdbc_type>
         <PrimaryKey>true</PrimaryKey>
      </FieldDescriptor>
      <FieldDescriptor id="3">
         <field.name>timestamp</field.name>
         <column.name>TIMESTAMP_</column.name>
         <jdbc_type>BIGINT</jdbc_type>
      </FieldDescriptor>
      <FieldDescriptor id="4">
